language: node_js

sudo: required

node_js:
  - "11.11.0"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8

before_install:
  - export CXX="g++-4.8"
  - npm install -g npm@latest
  - npm install -g truffle ganache-cli

install:
  - npm install 

before_script:
  - ganache-cli -p 8545 &
  - sleep 5

script:
  - truffle compile
  - truffle migrate
  - truffle test

after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls